name: ErfanGSI-build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Direct link/直链'
        required: true
        default: 'https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/5b29futu0vp7phbhv6vu0f62p96a1jff/dn94vskkuufpmvl7pad0o4fusoqfnv26/1681032150000/07821869990264611324/06960255461461367325/11C2tMHLe_-a-o3SyaD5RZkUk9BIW5WKx?e=download&ax=ALy03A5wKsWiq8DHe_Je6tmwiapU_cF1dr_ikHwg55pMUC4dfwkkndWCOk-PpcXABIJ85beQaQGUFdO33ydahWA2zhoNPoBpK7AIaRGAVDtYQ1jSOk3kahKmglsJVVWCofwc1euhVyMrjZXfbKKSdrYDAkxhwKGzVq5a5ODWadjyuth_MZadl4b8TLh5MZnpNO4lr2BpoTGfXR0jzhBYF1okUnRiMag8Tjgx68AXa-Iy4uO1RdtgnmBNbWVxUTivNMK3u46IXelv3WLzdqIAc8iFMT8YJ1oAVqxxVnPjk6b3XbsQ8_X_jR9GpiVSxNzwzzDlrt6osOiidVmYlMCVr_1g69mtDwsUNf1ymYMRvWESGwnXH2RoIv5q3-TqzE7dAzvJczXTsj_CYpddEa0eNdxcDX7dzgjUQWbbT8vpwqj7ED5Y6LItaIGqhZm-sUhNi8-VNAc-g4eKzjBjxUK3YVDkpjsp0gTCiN-vXKyyNgvFz_m4VgTxAD9YnVKimzHsSBBi-y2ky57oynSFyOX-Fz58OwcixBVbb4oYx4NOiBSYgVFCqdPud6VZDbq1togTR2_CJ1P1wTA8EqAOAmgoxy_c8ahrzG_7qNoEUh5zKkERKQtr_CKEttmyBjYvmaEarWeV-iq_-34MPrr32e_CmDqgNBStxCT05DM0UHm07AMN4sc2ekWHXrKaBPZ4XpBMVvU_sY72WA2o2d_ji6b4-7jjdDCjgskSCmSx2fJ-yQaGW21hOI1FbUTgXuMj2t595BV9gf93WgjyDf3EifA5epx0p7VnWq6W-hTw700j97LjGtX-VfakgTYOGfSPRtqlQhtrLmA2Hc4nIWGXJXgYJGj1Z20pGMGKpjIsRbW4XyglsnzvXw0VaMEc3OM2RL60We65XQ&uuid=edb69b0e-f439-4ec0-9a9f-432c9dc6d543&authuser=0&nonce=b3phh23gi15ki&user=06960255461461367325&hash=k90ilmqa6lpj9c06b8pvg1sif204vnna'
      REPACK_NAME:
        description: 'Compressed name/打包名称'
        required: true
        default: 'gsi.7z'
      ROM_TYPE:
        description: 'ROM type/ROM 类型'
        required: true
        default: 'Generic'

jobs:
  build_tosasitill_GSI:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取源代码
        uses: actions/checkout@main
        with:
          path: ErfanGSIs

      - name: 获取变量
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
          echo "BUILD_sTIME=$(TZ=Asia/Shanghai date -d @$(date +%s) +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV

      - name: 配置环境‌‌
        run: |
          sudo apt install -y git wget git gzip unzip curl axel aria2 zstd rename p7zip-full pigz

      - name: 获取 ErfanGSI 工具
        uses: actions/checkout@main
        with:
          repository: tosasitill/erfanSGSI
          path: ErfanGSIs

      - name: 更换 777 权限
        run: |
          sudo chmod 777 -R $GITHUB_WORKSPACE/ErfanGSIs

      - name: 修复意外退出
        run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh

      - name: 建立并配置 ErfanGSI 工具所需环境
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          sudo bash $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
          java -version
          pip3 install aligo

      - name: 下载 ROM 并制作 GSI
        run: |
          cd ${{ github.workspace }}/ErfanGSIs/
          sudo bash ./url2GSI.sh --ab ${{ github.event.inputs.ROM_URL }} ${{ github.event.inputs.ROM_TYPE }}

      - name: 压缩 GSI
        if: ${{ github.event.inputs.ALI }} != '1'
        run: |
          cd $GITHUB_WORKSPACE/ErfanGSIs
          pwd
          7za a -mmt16 -t7z -r tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} output/*
          ls "tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}"
          mkdir upload_ab
          ls upload_ab
          if [ $(ls -l tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | awk '{print $5}') -gt 2147483647 ]; then tar cvzpf - tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; else mv tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; fi

      - name: 上传至 Github Releases
        if: ${{ github.event.inputs.ALI }} != '1'
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{ github.workspace }}/ErfanGSIs/upload_ab/*"
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
